-- Insert data into the levels table with level_id included

-- Easy Levels (leveldifficulty = 1)
INSERT INTO level (levelid, levelname, wordcount, leveldifficulty, content) VALUES
(1, 'Cat on the Mat', 60, 1, 'The cat sat on the mat. It was a sunny day. The birds sang in the trees. The dog barked at the mailman. The kids played in the park. They had fun all day long. The sun shone bright in the sky. The flowers bloomed in the garden. A bee buzzed by the window. The children laughed and ran around.'),
(2, 'Jack and Jill''s Spill', 49, 1, 'Jack and Jill went up the hill to fetch a pail of water. Jack fell down and broke his crown, and Jill came tumbling after. The sky was blue, and the grass was green. Birds flew over the fields. The sheep grazed quietly. The farmer walked along the road.'),
(3, 'Red Riding''s Shortcut', 55, 1, 'Once upon a time, there was a little girl named Red Riding Hood. She went to visit her grandmother. She walked through the woods. She picked some flowers. She saw a wolf. The wolf was big and bad. He asked her where she was going. She told him. He ran ahead to the grandmother''s house.'),
(4, 'Fox''s Fancy Jump', 53, 1, 'The quick brown fox jumps over the lazy dog. This sentence uses every letter. Typing practice can be fun. Use simple words to build speed. Practice makes perfect. Keep your fingers on the home keys. Look at the screen, not at your hands. Type each word carefully. Do not rush. Accuracy is important.'),
(5, 'Mary''s Lamb Tale', 64, 1, 'Mary had a little lamb, its fleece was white as snow. Everywhere that Mary went, the lamb was sure to go. It followed her to school one day, which was against the rules. It made the children laugh and play, to see a lamb at school. The teacher turned it out, but still it lingered near. It waited patiently about till Mary did appear.'),
(6, 'Sunrise to Sunset', 59, 1, 'The sun rises in the east and sets in the west. Birds fly in the sky. Fish swim in the sea. Trees grow tall in the forest. The grass is green. The sky is blue. The clouds are white. The flowers are red, yellow, and pink. Children play in the park. Dogs bark at strangers. Cats purr when happy.'),
(7, 'Baker''s Dozen Delight', 66, 1, 'In a small town, there was a baker who made the best bread. People came from afar to buy his loaves. He used fresh flour and pure water. Every morning, he woke up early to knead the dough. The smell of baking filled the streets. Children loved his buns and cakes. The baker smiled as he saw happy faces. He worked hard but enjoyed his job.'),
(8, 'Zoo-tastic Adventure', 68, 1, 'At the zoo, the lions roared loudly. The monkeys swung from tree to tree. The elephants sprayed water with their trunks. The kids watched with wide eyes. They fed peanuts to the goats. The zookeeper told them about the animals. They learned that tigers have stripes. Zebras have black and white stripes. Giraffes have long necks to reach high leaves. They had a fun day at the zoo.'),
(9, 'Frog Meets Fish', 63, 1, 'Once there was a frog who lived in a pond. He liked to catch flies. One day, he met a fish. The fish said hello. They became friends. They played games in the water. The frog jumped on lily pads. The fish swam around him. They had fun every day. The frog told jokes. The fish laughed. They shared stories. They were happy.'),
(10, 'Rainbow After Rain', 67, 1, 'The rain fell softly on the ground. The children wore boots and coats. They splashed in puddles. They laughed and sang songs. The ducks quacked in the pond. The rain made the plants grow. After the rain, the sun came out. A rainbow appeared in the sky. The air smelled fresh and clean. They looked at the bright colors. Red, orange, yellow, green, blue, indigo, and violet.');

-- Medium Levels (leveldifficulty = 2)
INSERT INTO level (levelid, levelname, wordcount, leveldifficulty, content) VALUES
(11, 'Peaks, Crops, and Laughs', 76, 2, 'In the small village nestled between the mountains, residents lived a simple life. Each morning, the sun rose over the peaks, casting golden hues across the valley. Farmers tended their crops; children played in the fields. Sounds of laughter and scent of fresh bread filled the air. In the evenings, everyone gathered to share stories around the fire. The community was strong; people looked out for one another. Despite the simplicity, they were content and happy.'),
(12, 'Tick Tock, Sketch O''Clock', 79, 2, 'At the heart of the city stood a towering clock tower, its hands moving steadily through time. People hurried past, engrossed in their daily routines. Street vendors sold their goods, and musicians played melodies that echoed through the alleys. Amidst the hustle, a young artist sat sketching, capturing the essence of the city on paper. She observed the interactions, the fleeting smiles, and the shared moments. Though the city was vast and busy, connections were made in unexpected ways.'),
(13, 'Wind, Water, Win', 83, 2, 'On the shores of the vast lake, a sailing competition was about to begin. Boats of various sizes and colors lined up, sails billowing in the wind. Spectators gathered along the waterfront, cheering for their favorite teams. The signal was given, and the boats took off, cutting smoothly through the water. The sky was clear, and the sun shone brightly, adding to the excitement. As they navigated the course, skill and strategy were key. In the end, teamwork and perseverance led to victory.'),
(14, 'Lab Rats to Legends', 75, 2, 'In a hidden laboratory, scientists worked tirelessly on a groundbreaking project. The room was filled with equipment, screens displaying complex data. They were on the verge of a discovery that could change the world. Hours turned into days, but their dedication never wavered. Finally, the results confirmed their theories. Celebrations erupted; years of hard work had paid off. This innovation promised to improve lives and advance technology significantly. Their names would be remembered in history.'),
(15, 'Lost and Found in Leaves', 74, 2, 'An expedition set out to explore the depths of the ancient forest. Legends spoke of lost civilizations and hidden treasures. The team consisted of archaeologists, explorers, and guides familiar with the terrain. They trekked through dense foliage, navigating by compass and map. Along the way, they discovered ruins, artifacts, and clues to the past. Challenges arose, but they overcame them through cooperation and ingenuity. The journey was arduous but filled with wonder and excitement.'),
(16, 'Marshmallows and Memories', 78, 2, 'Under the starry night sky, a group of friends gathered around a campfire. They roasted marshmallows and shared stories, their faces illuminated by the flickering flames. The sounds of nature enveloped them: crickets chirping, leaves rustling in the breeze. The conversation drifted from lighthearted tales to deep reflections. Away from the distractions of modern life, they felt connected to each other and the world around them. It was a moment of peace and camaraderie they would always remember.'),
(17, 'Science Sparks', 80, 2, 'At the annual science fair, students displayed innovative projects and experiments. The auditorium buzzed with excitement as judges made their rounds. One exhibit showcased a sustainable energy solution using solar panels and wind turbines. Another featured a robotic arm programmed to perform intricate tasks. Visitors were impressed by the creativity and dedication of the young minds. Awards were given, but the true reward was the experience and knowledge gained. The event inspired many to pursue careers in science and technology.'),
(18, 'Monk Mode Moments', 74, 2, 'In a remote monastery, monks practiced meditation and mindfulness daily. The serene environment fostered introspection and spiritual growth. Bells chimed softly, marking the passage of time. Visitors came seeking wisdom and tranquility, guided by the teachings of the monks. The library held ancient texts, filled with philosophy and poetry. Life there was simple, focused on the essentials. The experience left a profound impact on those who ventured there, offering a new perspective on life.'),
(19, 'Forks and Friendship', 72, 2, 'During the international culinary festival, chefs from around the world showcased their best dishes. Aromas of exotic spices and flavors filled the air. Attendees sampled cuisines from different cultures, experiencing a global gastronomic journey. Cooking demonstrations and workshops allowed people to learn new techniques. The event celebrated diversity and the universal love of food. Friendships were formed over shared meals and conversations. It was a feast for the senses, leaving lasting memories.'),
(20, 'Mysteries in Manuscripts', 75, 2, 'In the grand library, the young scholar pored over ancient manuscripts. Dust motes danced in the sunlight streaming through tall windows. He sought answers to questions that had puzzled historians for centuries. The silence was broken only by the turning of pages. Hours slipped by unnoticed as he delved deeper into the texts. Finally, he found a clue that could unlock a long-lost secret. His heart raced with excitement at the prospect of new discoveries.');

-- Hard Levels (leveldifficulty = 3)
INSERT INTO level (levelid, levelname, wordcount, leveldifficulty, content) VALUES
(21, 'Spooky Action', 81, 3, 'The phenomenon of quantum entanglement defies classical intuitions about the separability of distant objects. When particles become entangled, the state of one instantaneously influences the state of another, regardless of the distance separating them. This non-local behavior has profound implications for the foundations of physics and challenges our understanding of causality and information transfer. Experimental validations of entanglement have been achieved through sophisticated setups involving photons and atoms, opening avenues for quantum computing and secure communication technologies based on quantum cryptography.'),
(22, 'When Paintings Sing', 79, 3, 'In the realm of abstract art, Wassily Kandinsky''s compositions represent a radical departure from representational aesthetics. His work explores the intrinsic connections between color, form, and emotion, positing that visual elements can evoke auditory sensations—a concept known as synesthesia. Kandinsky''s theoretical writings delve into the spiritual aspects of art, suggesting that creative expression transcends mere imitation of the physical world. His influence is evident in the development of modern art movements that emphasize subjective experience over objective reality.'),
(23, 'Mom''s Secret Code', 72, 3, 'The intricacies of mitochondrial DNA inheritance provide fascinating insights into evolutionary biology and genetics. Unlike nuclear DNA, mitochondrial DNA is inherited almost exclusively maternally, offering a unique lens through which to trace lineage and ancestral origins. Mutations in mitochondrial DNA can lead to a variety of metabolic disorders, underscoring its critical role in cellular energy production. Research into mitochondrial function has also revealed connections to aging processes and apoptotic mechanisms within cells.'),
(24, 'Trade Secrets', 86, 3, 'The economic principle of comparative advantage explains how countries benefit from specializing in the production of goods for which they have a lower opportunity cost. This theory, formulated by David Ricardo, underpins much of modern international trade policy. It suggests that even if one nation is less efficient in producing all goods compared to another nation, both can still gain from trade by focusing on industries where they are relatively more efficient. The implications of this theory extend to discussions on tariffs, trade agreements, and globalization.'),
(25, 'Thinking Traps', 73, 3, 'In the study of cognitive psychology, the concept of heuristics pertains to mental shortcuts that facilitate problem-solving and decision-making processes. While heuristics can speed up judgments, they often introduce biases and systematic errors. The availability heuristic, for example, leads individuals to overestimate the likelihood of events that are more memorable or emotionally charged. Understanding these cognitive biases is essential for fields like behavioral economics, where they can influence market behaviors and consumer choices.'),
(26, 'Slit Happens', 73, 3, 'The double-slit experiment fundamentally challenges our understanding of particle-wave duality in quantum mechanics. When electrons are fired at a barrier with two slits, they produce an interference pattern characteristic of waves, not particles. However, if one attempts to observe which slit an electron passes through, the interference pattern disappears, and particle-like behavior emerges. This paradox highlights the role of the observer in quantum phenomena and raises profound questions about the nature of reality.'),
(27, 'Quantum Codebreakers', 77, 3, 'The field of cryptography has evolved dramatically with the advent of quantum computing. Traditional encryption methods, such as RSA and ECC, rely on the computational difficulty of factoring large prime numbers or solving discrete logarithm problems. Quantum algorithms, like Shor''s algorithm, threaten to render these methods obsolete by solving such problems exponentially faster. Consequently, there''s a growing emphasis on developing quantum-resistant cryptographic techniques, including lattice-based, hash-based, and code-based cryptography, to ensure data security in a post-quantum world.'),
(28, 'When Stars Can''t Even', 76, 3, 'In astrophysics, the Chandrasekhar limit defines the maximum mass of a stable white dwarf star, approximately 1.4 times the mass of the Sun. Beyond this threshold, electron degeneracy pressure can no longer counteract gravitational collapse, leading to the formation of a neutron star or black hole. This limit is crucial for understanding the life cycles of stars and the mechanisms behind supernova explosions. Subrahmanyan Chandrasekhar''s work in this area significantly advanced the field of stellar evolution.'),
(29, 'Ecosystem Jenga', 71, 3, 'The intricate balance of ecological systems is exemplified by keystone species, which have a disproportionately large impact on their environment relative to their abundance. The removal of a keystone species can trigger cascading effects throughout the ecosystem, leading to significant changes in community structure and biodiversity. Conservation efforts often prioritize these species to maintain ecological equilibrium. Understanding the roles of such species is vital for ecological research and environmental management practices.'),
(30, 'To Be or Nah?', 67, 3, 'The philosophy of existentialism explores the individual''s experience in an apparently meaningless or absurd world. Thinkers like Jean-Paul Sartre and Albert Camus grappled with themes of freedom, choice, and responsibility. Existentialism posits that individuals must create their own meaning through authentic actions and decisions. This perspective challenges traditional philosophical notions of objective truths and predetermined purposes, emphasizing instead the subjective and often challenging journey of human existence.');