-- Remove current scores and levels
DELETE FROM score;
DELETE FROM level;

-- Easy Levels (leveldifficulty = 1)
INSERT INTO level (levelid, levelname, wordcount, leveldifficulty, content) VALUES
(1, 'A Day at the Beach', 34, 1, 'The sun shone brightly in the sky. The sand was warm under our feet. We built sandcastles and splashed in the waves. It was a perfect day.'),
(2, 'The Lost Puppy', 32, 1, 'Tom found a puppy in the park. The puppy was lost and hungry. He gave it water and took it home. His parents agreed to keep it. They named the puppy Buddy.'),
(3, 'A Trip to the Zoo', 34, 1, 'Jenny went to the zoo with her family. She saw lions, tigers, and bears. The monkeys were her favorite. They swung from the trees and made funny faces. She had a wonderful day.'),
(4, 'First Day at School', 33, 1, 'Emma was nervous about her first day at school. She met her teacher and new friends. They played games and learned the alphabet. By the end of the day, she was happy.'),
(5, 'The Big Game', 31, 1, 'The team practiced hard all week. On Saturday, they played their first game. They worked together and scored many goals. Everyone cheered when they won.'),
(6, 'Baking Cookies', 32, 1, 'Mom and I baked cookies today. We mixed flour, sugar, and eggs. The kitchen smelled delicious. We shared the cookies with our neighbors.'),
(7, 'The Birthday Party', 30, 1, 'Sam invited all his friends to his birthday party. They played games and ate cake. He opened presents and thanked everyone. It was a fun day.'),
(8, 'Rainy Day Fun', 31, 1, 'It rained all day, so we stayed inside. We drew pictures and read books. Dad taught us how to play chess. The day passed quickly.'),
(9, 'The Kite Flying', 33, 1, 'The wind was strong, perfect for flying kites. We ran across the field, and our kites soared. They danced in the sky. We laughed and chased each other.'),
(10, 'Helping Grandma', 31, 1, 'We visited Grandma on Sunday. We helped her in the garden. We planted flowers and watered them. She thanked us with cookies. We promised to come back soon.');

-- Medium Levels (leveldifficulty = 2)
INSERT INTO level (levelid, levelname, wordcount, leveldifficulty, content) VALUES
(11, 'The Mountain Hike', 62, 2, 'Our family decided to hike up the mountain. The trail was steep and rocky. We saw birds and small animals along the way. The view from the top was breathtaking. We could see the entire valley below. We ate our lunch while enjoying the scenery. The hike down was easier. We were tired but happy after the adventure.'),
(12, 'Science Fair Project', 59, 2, 'For the science fair, Lisa built a volcano model. She researched how volcanoes erupt. Using baking soda and vinegar, she demonstrated an eruption. Her project impressed the judges. She explained the science behind it confidently. She won first prize. Her parents were proud of her achievement. She inspired her classmates to explore science.'),
(13, 'The School Play', 60, 2, 'The students prepared for the school play for weeks. They memorized lines and practiced their roles. The costumes were colorful and well-designed. On the night of the performance, the auditorium was full. The play was a success. The audience applauded loudly. The actors felt a great sense of accomplishment. They celebrated with a party afterwards.'),
(14, 'The New Neighbor', 61, 2, 'A new family moved into the house next door. They had a son named Alex. He was shy at first. We invited him to play soccer with us. He turned out to be a great player. Soon, he became our friend. His family invited us over for dinner. We were happy to have new neighbors.'),
(15, 'Camping Trip', 63, 2, 'During the summer vacation, we went camping in the forest. We set up tents and gathered firewood. At night, we sat around the campfire telling stories. The stars were bright in the clear sky. We heard owls hooting and leaves rustling. In the morning, we cooked breakfast over the fire. It was a memorable experience.'),
(16, 'The Art Competition', 59, 2, 'Maria loved painting and decided to enter an art competition. She spent days working on her piece. Her painting depicted a serene landscape with mountains and rivers. At the exhibition, many admired her work. Although she didn\'t win, she was proud of her effort. The experience motivated her to keep improving.'),
(17, 'The Robotics Club', 60, 2, 'James joined the robotics club at school. They worked on building a robot for a competition. He learned about coding and electronics. The team collaborated to solve problems. On the day of the competition, their robot performed well. They won second place. James enjoyed being part of the team and learning new skills.'),
(18, 'A Trip to the Museum', 62, 2, 'Our class visited the history museum. We saw ancient artifacts and learned about different cultures. The dinosaur exhibit was fascinating. We listened to the guide explain how fossils are formed. In the interactive section, we tried on historical costumes. The trip was both educational and fun. It sparked our interest in history.'),
(19, 'The Music Festival', 61, 2, 'The town held an annual music festival. Bands from various places performed. There were food stalls and games. We listened to different genres of music. The atmosphere was lively. In the evening, fireworks lit up the sky. It was a wonderful event that brought the community together.'),
(20, 'The Mystery Book', 59, 2, 'Emily found an old book in the attic. It was a mystery novel she had never heard of. She began reading and couldn\'t put it down. The plot was intriguing. She solved the mystery along with the characters. It inspired her to write her own stories. She discovered a passion for writing.');

-- Hard Levels (leveldifficulty = 3)
INSERT INTO level (levelid, levelname, wordcount, leveldifficulty, content) VALUES
(21, 'The Astronomer''s Discovery', 90, 3, 'Dr. Thompson gazed through the powerful telescope, observing distant galaxies. The cosmos was vast and enigmatic. He noticed an unusual phenomenon—a star exhibiting irregular luminosity patterns. He hypothesized that it might be orbiting a black hole or perhaps being obscured by an exoplanet with a peculiar atmosphere. He recorded his observations meticulously. Sharing his findings with colleagues, they debated the possible explanations. Further analysis and peer reviews were necessary. This discovery could contribute significantly to astrophysics and our understanding of the universe.'),
(22, 'The Invention of the Telegraph', 89, 3, 'In the nineteenth century, Samuel Morse revolutionized communication with the invention of the telegraph. Utilizing electric signals transmitted over wires, messages could be sent across vast distances almost instantaneously. Morse code, a system of dots and dashes representing letters and numbers, was developed to encode these messages. The telegraph had profound impacts on society, facilitating rapid news dissemination and altering the dynamics of commerce and warfare. It marked the beginning of an era where information could traverse the globe at unprecedented speeds.'),
(23, 'The Genetic Code Breakthrough', 88, 3, 'The discovery of the DNA double helix structure by Watson and Crick was a monumental achievement in molecular biology. It unveiled the mechanism by which genetic information is stored and replicated. The pairing of nucleotide bases—adenine with thymine, and guanine with cytosine—explained how genetic instructions are preserved during cell division. This breakthrough laid the foundation for advances in genetics, biotechnology, and medicine. Understanding DNA\'s role enabled developments such as genetic engineering, genome sequencing, and targeted therapies for hereditary diseases.'),
(24, 'The Renaissance''s Influence', 91, 3, 'The Renaissance was a pivotal period in European history, marking a resurgence of interest in classical art, literature, and philosophy. Humanism emerged, emphasizing the value of human potential and achievements. Artists like Leonardo da Vinci and Michelangelo produced masterpieces that showcased advanced techniques in perspective and anatomy. The invention of the printing press by Gutenberg facilitated the spread of knowledge. This era significantly influenced modern science, politics, and culture, laying the groundwork for the Enlightenment and shaping the course of Western civilization.'),
(25, 'Quantum Mechanics Paradoxes', 87, 3, 'Quantum mechanics presents several paradoxes that challenge classical physics. Schrödinger\'s cat thought experiment illustrates the concept of superposition, where a system can exist in multiple states simultaneously until observed. The Heisenberg Uncertainty Principle asserts that certain pairs of physical properties cannot be precisely measured simultaneously. These phenomena have profound implications for our understanding of reality. Despite seeming counterintuitive, quantum mechanics accurately predicts experimental results and is fundamental to technologies like semiconductors and MRI machines.'),
(26, 'The Theory of Relativity', 89, 3, 'Albert Einstein\'s Theory of Relativity transformed our comprehension of space, time, and gravity. The Special Theory of Relativity introduced the idea that the laws of physics are the same for all non-accelerating observers and that the speed of light is constant regardless of the observer\'s motion. It led to the famous equation E=mc², indicating the equivalence of mass and energy. The General Theory of Relativity expanded on this, describing gravity as the curvature of spacetime caused by mass. These theories have been confirmed by numerous experiments and observations.'),
(27, 'Artificial Intelligence Ethics', 88, 3, 'As artificial intelligence (AI) advances, ethical considerations become increasingly critical. Issues such as bias in algorithms, privacy concerns, and the potential for autonomous systems to make decisions without human oversight are central topics of discussion. The development of AI requires careful regulation to ensure it benefits society while minimizing risks. Philosophers and technologists debate the implications of machine consciousness and the moral status of AI entities. Establishing ethical guidelines is essential for responsible innovation in this rapidly evolving field.'),
(28, 'Climate Change Challenges', 90, 3, 'Climate change poses significant challenges globally, affecting ecosystems, economies, and communities. Rising temperatures lead to melting polar ice caps, sea-level rise, and increased frequency of extreme weather events. Addressing climate change requires international cooperation to reduce greenhouse gas emissions, transition to renewable energy sources, and implement sustainable practices. Scientific research informs policy decisions, while technological advancements offer solutions for mitigation and adaptation. Public awareness and education are crucial in driving collective action to combat this pressing issue.'),
(29, 'The Evolution of Language', 88, 3, 'Language evolution is a complex process influenced by social, cultural, and cognitive factors. Historical linguistics studies how languages change over time, including phonetic shifts, grammatical transformations, and vocabulary expansion. The development of pidgins and creoles demonstrates how new languages can emerge from contact between different linguistic communities. Technological advancements, such as the internet and social media, accelerate language change by facilitating rapid communication and the creation of new slang and expressions. Understanding language evolution enhances our comprehension of human history and social dynamics.'),
(30, 'Philosophy of Mind', 89, 3, 'The philosophy of mind explores the nature of consciousness, mental states, and their relationship to the physical body. Dualism posits that the mind and body are distinct entities, while physicalism argues that mental processes are entirely physical. Questions about subjective experience, known as qualia, challenge our understanding of perception and reality. The mind-body problem remains a central debate, with implications for artificial intelligence and cognitive science. Interdisciplinary approaches aim to bridge gaps between philosophy, neuroscience, and psychology to unravel the mysteries of consciousness.');